### ISSUE TITLE
Template Sensor and HVAC Mode Issue

### ISSUE THREAD

**Issue by Korkuttum** [EnzoD86/tuya-smart-ir-ac#35]
Hello, your project is great, I just wanted to make a few suggestions for improvements.

* 'Template' sensors are not being added as sensors.
* When the target temperature is changed and the air conditioner is off, the 'HVAC' mode is also turned on."
* You can add support for the Turkish (TR) language, I have adjusted the file for you.
[tr.json](https://github.com/user-attachments/files/18362477/tr.json)

**Comment by EnzoD86** [comment]
Hi, thank you for your feedback, and not only!

For your suggestions, I will answer you point by point:

1. for template sensor, I imagine you are referring to the temperature and humidity sensors; they are not exposed because they are already real sensors that are pre-configured and it seemed superfluous to expose them; if you explain to me why this functionality could be useful to you, I can consider making this change!
2. the integration is only a bridge with the tuya api and therefore I have no control over this unfortunately;
3. regarding the implementation of the Turkish language, it will be done in the next few days!

Thanks for your feedback!

**Comment by Korkuttum** [comment]
1.	The template sensor offset value is important for using a different sensor that I define.
2.	I believe this can be handled on your side. In the Tuya app, when HVAC is off, the temperature cannot be changed. Here, when the temperature changes, the HVAC mode is activated, but there is no interaction with the device.
3.	Thank you!

**Comment by EnzoD86** [comment]
1. the reason is not very clear, but I could make it configurable whether to expose the configured sensors or not;
2. that's right! from tuya or smartlife you can't change anything if the air conditioner is off!
But... I purposely didn't want to add this type of control because we're still talking about a virtual device!
If I had added this restriction, and you turn on the air conditioner from the physical remote control, home assistant will continue to see the air conditioner as off and to be able to change the temperature from HA you will first have to turn it on and then you will be able to change the temperature.
You would have an extra step that you don't have at the moment (especially if you have to do this operation from a voice assistant). I hope I was clear.
that said... this could also be made configurable, so that everyone can then use the mode that is most convenient and/or preferable to them.

I'll do some testing in the next few days and try to release a beta version with these changes.
Thanks again for your feedback!

**Comment by Korkuttum** [comment]
1. Template sensors can also be useful for those who combine multiple sensors or calculate averages. This functionality could be beneficial for such use cases as well. 

2.Thank you very much for your interest. There could be a setting to force the HVAC mode to turn on when the temperature changes. Actually, I think the main issue is that even though it shows as turned on in Home Assistant, the device itself doesn’t take any action. Perhaps sending the command to the device simultaneously would make sense. This way, the device and Home Assistant would stay synchronized.

**Comment by EnzoD86** [comment]
1. when you talk about template sensors, do you mean that the integration should expose the 2 sensors (temperature and humidity)?
2. maybe then I didn't understand the problem, initially I understood that you didn't like that by changing the temperature the air conditioner turned on.
Instead from this last message I deduce that by changing the temperature for home assistant the air conditioner turns on but actually it remains off. So can you confirm that this is the case?
In that case then we have to adopt another type of solution... unfortunately tuya has a way of managing air conditioners that is proving to be very problematic and very different based on the brands and models.
Sending a simultaneous command could solve it but we need to do some tests.

**Comment by Korkuttum** [comment]
1.	Yes, I can’t see the sensors I created as virtual sensors in the configuration screen. For example:

sensor:
  unique_id: combined_temp_sensor
  unit_of_measurement: "°C"
  state: >
    {% if states('sensor.termostat_thermostat_temperature') not in ['unavailable', 'unknown', 'null'] %}
      {{ states('sensor.termostat_thermostat_temperature') | float }}
    {% else %}
      {{ states('sensor.ir_remote_temperature2') | float }}
    {% endif %}


2.	Your new understanding is correct.! As shown in the video, when the target temperature changes, the HVAC appears to turn on, but the device doesn’t actually turn on. In this case, you can choose one of the following options:
	1.	The device can be turned on.
	2.	When the temperature changes, the device doesn’t turn on in reality or in Home Assistant.

You can decide which option to prefer.

[image](https://github.com/user-attachments/assets/7023e64d-19cc-4a4d-8908-3ef824ce40f0)

https://github.com/user-attachments/assets/b59b910f-7e83-4d57-baa8-ee59363fe738

**Comment by EnzoD86** [comment]
Hii, sorry for my late reply.
I took a few days to analyze the integration, because it was a few months since I modified it.

Regarding point 1, there are no problems, in the next version the configured sensors will be exposed as normal temperature and humidity sensors.

Regarding point 2, now the problem is clear; since I do not want to change the current operation so as not to cause problems with other air conditioners, I can try to solve it by adding a compatibility option that turns on the air conditioner before changing the temperature.

To try to make an accurate fix, I would need these tests, before proceeding:
1. with the air conditioner off, if you change the fan speed do you have the same problem as the temperature (which turns on in HA but the device remains off)?
2. surely the hvac mode works correctly (otherwise you would have reported it to me), but did you have to set something special in the compatibility options?

Thanks

**Comment by Korkuttum** [comment]
1.	Yes, it shows as on in Home Assistant, but the device remains off.
	2.	The HVAC mode works perfectly, and I didn’t make any adjustments.

Note: In my opinion, the necessary setting should be: Should the HVAC mode be forced to turn on when the target temperature changes?

Also, thank you very much for your attention!

**Comment by EnzoD86** [comment]
1. I was sure it would behave the same way.
2. Ok, yes because when you set the hvac mode a multiple command is sent which also includes turning on the device.

As I wrote to you in some previous posts, I am not sure that you can change the temperature with the device turned off.
In fact, as we said, smart life and tuya prevent you from doing so by deactivating the commands to do so.

I did a test with my device and I cannot change the temperature while keeping the air conditioner turned off.

This is why the solution that should create fewer problems is to add a flag that, if active, sends a turn-on command before changing the temperature and/or fan speed.

**Comment by Korkuttum** [comment]
Yes, I also think adding a flag would be appropriate.

**Comment by EnzoD86** [comment]
Hi, I released a beta version that you can find here: [2025.1.0.a](https://github.com/EnzoD86/tuya-smart-ir-ac/releases/tag/2025.1.0.a)
It is possible that further changes will still be made, but in the meantime let me know if activating the compatibility options solves the problem.
Thanks

**Comment by Korkuttum** [comment]
* Configured temperature and humidity sensors are still not selectable.
* The compatibility modes are working well. When I select "only if off" or "always," the device integrates seamlessly with Home Assistant, which is great. However, if I select the "never" flag, the device still shows as turned on in Home Assistant, but it does not physically turn on.

**Comment by EnzoD86** [comment]
hi,
for the first point, we probably didn't understand each other then!
I thought you needed the integration to expose the sensors configured as integration sensors!
Instead you want the template sensors to be selectable by the integration config flow!

To do this you don't need to make any changes, just define in your template sensor add the device_class property and set it to temperature or humidity based on the type of sensor you are creating.

Example:
```
sensor:
  unique_id: combined_temp_sensor
  unit_of_measurement: "°C"
  device_class: "temperature"
  state: >
    {% if states('sensor.termostat_thermostat_temperature') not in ['unavailable', 'unknown', 'null'] %}
    {{ states('sensor.termostat_thermostat_temperature') | float }}
    {% else %}
    {{ states('sensor.ir_remote_temperature2') | float }}
    {% endif %}

```
I will do a rollback to remove the change I had made.

As for the second point, it works exactly as you said! Selecting the flag on "never" continues to work as before making this change. In your case you must in fact select "only if off" or "always" (depends on what you prefer); "only if off" is not recommended because it could create problems if a misalignment is created between the state on ha and the state of the device.

**Comment by Korkuttum** [comment]
Okay, it works seamlessly with the device_class.

There is no issue with the second point either.

Thank you very much for your attention.
