### ISSUE TITLE
I can't configure.

### ISSUE THREAD

**Issue by yurkila** [EnzoD86/tuya-smart-ir-ac#71]
I installed the extension, rebooted the system, and when I added the integration (clean install), I received the following error: 
Tuya Smart IR AC

Integration not configured or incorrect credentials.

 I tried reinstalling, but it still didn't work.

**Comment by EnzoD86** [comment]
hi, did you add the configuration in the configuration.yaml?

**Comment by yurkila** [comment]
Yes, I have gone to the address (I have the HA operating system): /config/configuration.yaml and edited it:

# Loads default set of integrations. Do not remove.

default_config:

# Load frontend themes from the themes folder

frontend:

themes: !include_dir_merge_named themes

automation: !include automations.yaml

script: linclude scripts.yaml

scene: linclude scenes.yaml

art go here:

access_id: "xxxxxxxxxxxxxxxxxxxxx"

access_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

country: "EU"

update_interval: 60

I have also tried without quotes and it doesn't work for me either.

**Comment by EnzoD86** [comment]
you forgot "tuya_smart_ir_ac:"
it must be like this:

```
tuya_smart_ir_ac:
  access_id: "tuya_access_id_example"
  access_secret: "tuya_access_secret_example"
  country: "EU"
```

**Comment by yurkila** [comment]
Edited and it still doesn't work, I deleted the last line and I can't get it to work, it always says the same error, the log tells me this:

Registrador: homeassistant.setup
Fuente: setup.py:279
Ocurrió por primera vez: 15:46:06 (1 ocurrencia)
Última vez registrado: 15:46:06

Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.

Este error se originó a partir de una integración personalizada.

Registrador: custom_components.tuya_smart_ir_ac
Fuente: custom_components/tuya_smart_ir_ac/__init__.py:59
integración: tuya_smart_ir_ac (documentación, problemas)
Ocurrió por primera vez: 15:46:06 (1 ocurrencia)
Última vez registrado: 15:46:06

Tuya Open API login error

**Comment by EnzoD86** [comment]
from the log it looks like a login error. check that the credentials are correct

**Comment by davidbaldwin71** [comment]
I am getting the same error as above and have copied the id and secret straight from the Tuya platform for my project.  I am using "US" as the country.

**Comment by klashfoto** [comment]
I am having the same issue, Stuck in "Integration not configured or incorrect credentials."

tuya_smart_ir_ac:
  access_id: "copy_straight_from_tuya"
  access_secret: "copy_straight_from_tuya"
  country: "US"

**Comment by EnzoD86** [comment]
You need to look for the error in the Home Assistant logs.

> I am having the same issue, Stuck in "Integration not configured or incorrect credentials."
> 
> tuya_smart_ir_ac: access_id: "copy_straight_from_tuya" access_secret: "copy_straight_from_tuya" country: "US"

**Comment by davidbaldwin71** [comment]
Logger: custom_components.tuya_smart_ir_ac
Source: custom_components/tuya_smart_ir_ac/__init__.py:59
integration: tuya_smart_ir_ac ([documentation](https://github.com/EnzoD86/tuya-smart-ir-ac), [issues](https://github.com/EnzoD86/tuya-smart-ir-ac/issues))
First occurred: July 9, 2025 at 4:35:27 PM (1 occurrence)
Last logged: July 9, 2025 at 4:35:27 PM

Tuya Open API login error

The above is all that is seen on the HA Core logs

**Comment by EnzoD86** [comment]
Hi, try adding these lines to your configuration file:

```
logger:
  logs:
    custom_components.tuya_smart_ir_ac: debug
```

then restart HA and see if there is any more useful information in the log.

**Comment by davidbaldwin71** [comment]
Thanks, nothing more is seen in the logs.

**Comment by EnzoD86** [comment]
Verify that the datacenter you set on the integration is the same as the one configured on the Tuya platform

**Comment by davidbaldwin71** [comment]
I have "US" set as the Tuya developer platform is "Data Center : Western America Data Center"

**Comment by EnzoD86** [comment]
As another user suggested, try to see if this guide can help you.

https://github.com/azerty9971/xtend_tuya/blob/main/docs/renew_cloud_credentials.md

**Comment by klashfoto** [comment]
"Logger: homeassistant.bootstrap
Source: bootstrap.py:1006
First occurred: 15:25:17 (3 occurrences)
Last logged: 15:27:17

Waiting on integrations to complete setup: {('tuya_smart_ir_ac', None): 508717.216069059}"

I'm getting this warning, still Integration not configured or incorrect credentials.

**Comment by davidbaldwin71** [comment]
> As another user suggested, try to see if this guide can help you.
> 
> https://github.com/azerty9971/xtend_tuya/blob/main/docs/renew_cloud_credentials.md

My IoT service status is "In Service" so no need to follow the rest of this guide.

**Comment by EnzoD86** [comment]
Also check out the "IR Control Hub Open Service" service

**Comment by davidbaldwin71** [comment]
Have checked and that is also "In Service"

**Comment by eu-vd** [comment]
I have no more ideas...

**Comment by EnzoD86** [comment]
I have no more ideas...

**Comment by hipapit** [comment]
Hi, I'm having these errors, and I can't add the integration

Registo: homeassistant.setup
Origem: setup.py:278
Primeira ocorrência: 10:45:04 (1 ocorrência)
Último registo: 10:45:04

Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.


And this...

Registo: custom_components.tuya_smart_ir_ac
Origem: custom_components/tuya_smart_ir_ac/__init__.py:59
integração: Tuya Smart IR AC ([documentação](https://github.com/EnzoD86/tuya-smart-ir-ac), [problemas](https://github.com/EnzoD86/tuya-smart-ir-ac/issues))
Primeira ocorrência: 10:45:04 (1 ocorrência)
Último registo: 10:45:04

Tuya Open API login error




> Como outro usuário sugeriu, tente ver se este guia pode ajudar você.
> 
> https://github.com/azerty9971/xtend_tuya/blob/main/docs/renew_cloud_credentials.md

I did this, but mine is already showing the message "In Service"

**Comment by hipapit** [comment]
No records were found for the search term 'tuya_smart_ir_ac'.
2025-07-17 10:02:57.791 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:03:32.785 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Tuya Open API login error
2025-07-17 10:03:32.788 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.
2025-07-17 10:08:27.573 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:08:48.806 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:09:52.612 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:10:27.687 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Tuya Open API login error
2025-07-17 10:10:27.690 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.
2025-07-17 10:15:30.144 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:20:12.074 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:20:41.928 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Tuya Open API login error
2025-07-17 10:20:41.935 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.
2025-07-17 10:28:19.787 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:28:52.781 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Tuya Open API login error
2025-07-17 10:28:52.785 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.
2025-07-17 10:33:52.816 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:34:19.370 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Tuya Open API login error
2025-07-17 10:34:19.384 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.
2025-07-17 10:43:38.406 WARNING (SyncWorker_12) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:44:36.761 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 10:45:04.112 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Tuya Open API login error
2025-07-17 10:45:04.133 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.
2025-07-17 11:21:16.134 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 11:24:09.611 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-07-17 11:24:43.996 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Tuya Open API login error
2025-07-17 11:24:43.999 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.

**Comment by EnzoD86** [comment]
I've released version 2025.7.0, which improves the error message when login fails. Please update to the latest version and let me know what error you get.

**Comment by hipapit** [comment]
I updated and restarted Home Assistant, but these messages still appear. I'm going to reset and reconfigure it from scratch to see if there's something causing this error.

Registo: homeassistant.setup
Origem: setup.py:278
Primeira ocorrência: 13:23:58 (1 ocorrência)
Último registo: 13:23:58

Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.

And this...

Este erro teve origem numa integração personalizada.

Registo: custom_components.tuya_smart_ir_ac
Origem: custom_components/tuya_smart_ir_ac/__init__.py:59
integração: Tuya Smart IR AC (documentação, problemas)
Primeira ocorrência: 13:23:58 (1 ocorrência)
Último registo: 13:23:58

Tuya Open API login error: your ip(191.22.21.196) don't have access to this API


Registo: py.warnings
Origem: components/cast/__init__.py:7
Primeira ocorrência: 13:23:52 (1 ocorrência)
Último registo: 13:23:52

/usr/local/lib/python3.13/site-packages/google/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81. __import__('pkg_resources').declare_namespace(__name__)

**Comment by EnzoD86** [comment]
now you can finally see the error:  Tuya Open API login error: your ip(191.22.21.196) don't have access to this API

So the problem certainly isn't related to the integration. Try googling it and see if you find anything.

**Comment by hipapit** [comment]
Great, my friend. I'll do some research and if I find a solution, I'll comment here. Thank you so much! You're the best!

Hey, I have another question about TV integration via IR and receivers via IR. Does it work with this same integration?

**Comment by hipapit** [comment]
Dude, after racking my brains trying to figure out what was causing the error and redoing everything, I realized that I was putting the access ID and secret ID between curly braces "<>" in the code. After removing it, it worked fine. 

Because I took it as a basis from another guy's video, and in his it worked with the keys, but in mine it only worked without the keys.

**Comment by davidbaldwin71** [comment]
Thanks for the update to the integration - the logs now show "Tuya Open API login error: your ip(XX04:XX00:4128:XX00:d393:XXc:d147:XX75) don't have access to this API"

Unfortunately you can't add an IPv6 address to the Tuya project whitelist so will look to disable IPv6 on my Internet connection and try again.

**Comment by EnzoD86** [comment]
> Thanks for the update to the integration - the logs now show "Tuya Open API login error: your ip(XX04:XX00:4128:XX00:d393:XXc:d147:XX75) don't have access to this API"
> 
> Unfortunately you can't add an IPv6 address to the Tuya project whitelist so will look to disable IPv6 on my Internet connection and try again.

In your Tuya Developer Platform, is the Cloud Authorization IP Allowlist enabled or disabled?

<img width="417" height="65" alt="Image" src="https://github.com/user-attachments/assets/5ba4840d-0639-4143-9599-aa1df22d7800" />

If it is activated, deactivate it.

**Comment by EnzoD86** [comment]
> Hey, I have another question about TV integration via IR and receivers via IR. Does it work with this same integration?

If you have set up your remotes on the Tuya/SmartLife app, you should be able to get them to work with this integration.

**Comment by davidbaldwin71** [comment]
I have disabled IPv6 on my HA server and this has allowed the connection successfully now.  Thank you very much for your work on this, the integration is great and the extra logging was essential on solving this.

Much appreciated! Thanks again.

**Comment by klashfoto** [comment]
Also got it working after ipv6 disabled, thanks!

**Comment by jtaveras65** [comment]
I was able to set it up, but it's asking me for this information. Where can I get it?

<img width="473" height="387" alt="Image" src="https://github.com/user-attachments/assets/c387830d-013f-4c4d-9835-a72ec2adb1f3" />

**Comment by EnzoD86** [comment]
> I was able to set it up, but it's asking me for this information. Where can I get it?
> 
> <img alt="Image" width="473" height="387" src="https://private-user-images.githubusercontent.com/71199594/468126846-c387830d-013f-4c4d-9835-a72ec2adb1f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTI4NjU4NjQsIm5iZiI6MTc1Mjg2NTU2NCwicGF0aCI6Ii83MTE5OTU5NC80NjgxMjY4NDYtYzM4NzgzMGQtMDEzZi00YzRkLTk4MzUtYTcyZWMyYWRiMWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzE4VDE5MDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmMTRiOWY5Yjg3ZTFiYTFkYmNjYmQxMWE4M2U5ZmJiMzFjYjQ4M2VlZWVjZTIxODEyZjcwNTkzYWQ1NjRhOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eXL91oS1B4EcGrWIixlnDz8pNwSxi9bC5Rg3PaRto5I">

Please read the readme on the project's home page!
